version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin1
    ports:
      - 3306:3306
    volumes:
      - ./DATABASE/data.sql:/docker-entrypoint-initdb.d/data.sql
      - mysql_data:/var/lib/mysql

  backend:
    build: ./BACKEND
    volumes:
      - ./BACKEND/app:/usr/src/app
    ports:
      - 8000:8000
    working_dir: /usr/src/app/PVAPIRest
    depends_on:
      - database
    command: >
      sh -c "
        sleep 10 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: ./front-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-app:/app
    depends_on:
      - backend

volumes:
  mysql_data:
