# version: '3.5'
services:
  database:
     image: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=admin1
     volumes:
       - ./DATABASE/data.sql:/docker-entrypoint-initdb.d/data.sql
       - mysql_data:/var/lib/mysql

  backend:
    build: ./BACKEND
    volumes:
      - ./BACKEND/app/.:/usr/src/app
    ports:
      - 8000:8000
    working_dir: /usr/src/app/PVAPIRest
    depends_on:
      - database
    tty: true
    stdin_open: true
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    image: httpd:latest
    ports:
      - 8080:80

volumes:
  mysql_data:
