# Generated by Django 5.2.3 on 2025-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=100)),
                ('avalible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'libros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
