# Generated by Django 5.2.3 on 2025-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baterias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('alto', models.IntegerField()),
                ('voltaje', models.IntegerField()),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('consumo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'baterias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inversores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.IntegerField()),
                ('tension_admisible', models.IntegerField()),
                ('consumo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_vida', models.IntegerField()),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'inversores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Irradiacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'irradiacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paneles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.IntegerField()),
                ('consumo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_vida', models.IntegerField()),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.IntegerField()),
                ('alto', models.IntegerField()),
            ],
            options={
                'db_table': 'paneles',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
